CTCTRADERS-2050  - update  cancellationConfirmation page andcreate cancellationReason page.
hmrc/declare-transit-movement-cancellation-frontend pull request #11
Opened 2021-03-01 15:51 UTC by kenneth-rayner

2021-03-02 09:29 UTC, kevincoatsworth approved these changes

2021-03-08 16:40 UTC, amaalali requested changes

2021-03-08 16:40 UTC, amaalali commented on app/controllers/actions/FakeDataRetrievalAction.scala
> +  def apply(lrdepartureIdn: DepartureId): ActionTransformer[IdentifierRequest, OptionalDataRequest] =
A typo with the rename
```suggestion
  def apply(departureId: DepartureId): ActionTransformer[IdentifierRequest, OptionalDataRequest] =
```

2021-03-08 16:40 UTC, amaalali commented on app/forms/CancellationReasonFormProvider.scala
> +  val stringFieldRegex = "[\\sa-zA-Z0-9&'@/.\\-? ]*"
This should be centralised since this applies to this field and any other fields that may get added. @kenneth-rayner  similar to what was done in Departures FE

2021-03-08 16:40 UTC, amaalali commented on app/forms/CancellationReasonFormProvider.scala
> +        .verifying(maxLength(350, "cancellationReason.error.length"))
Also move this constant out

2021-03-08 16:40 UTC, amaalali commented on app/models/LocalReferenceNumber.scala
>    private val lrnFormat = """^([a-zA-Z0-9-_]{1,22})$""".r
Users aren't entering the LRN on this service so we can relax the validation

2021-03-08 16:40 UTC, amaalali commented on app/config/FrontendAppConfig.scala
> +//  val departureFullServiceUrl = configuration.get[Service]("microservice.services.departures").fullServiceUrl
If this isn't needed we can remove

2021-03-08 16:40 UTC, amaalali commented on app/repositories/SessionRepository.scala
> +    collection.flatMap(_.find(Json.obj("_id" -> departureId), None).one[UserAnswers])
Can we update so that on a get we keep the session alive? This may need to go into a follow up PR. See example here: https://github.com/hmrc/hmrc-frontend-scaffold.g8/blob/play-frontend-upgrade/src/main/g8/app/repositories/SessionRepository.scala#L42-L49

2021-03-08 16:40 UTC, amaalali commented on conf/views/cancellationReason.njk
> +        <form action="{{ routes.controllers.CancellationReasonController.onSubmit(departureId, mode).url }}" method="post">
We need to pass in the routes via the controller

2021-03-08 16:40 UTC, amaalali commented on conf/views/confirmCancellation.njk
> +        <form action="{{ routes.controllers.ConfirmCancellationController.onSubmit(departureId, mode).url }}" method="post">
We need to pass in the routes via the controller

2021-03-08 16:40 UTC, amaalali commented on test/base/SpecBase.scala
> +  implicit val hc: HeaderCarrier = HeaderCarrier(Some(Authorization("BearerToken")))
Why is this needed globally, would this only be needed in controller specs / connector specs?

2021-03-08 16:40 UTC, amaalali commented on test/controllers/CancellationSubmissionConfirmationControllerSpec.scala
> +class CancellationSubmissionConfirmationControllerSpec extends SpecBase with MockitoSugar with JsonMatchers with MockNunjucksRendererApp {
We should make the tests consistent with `CancellationReasonControllerSpec`

2021-03-08 16:40 UTC, amaalali commented on app/models/LocalReferenceNumber.scala
> +      lrn.value
We don't need a `PathBindable[LocalReferenceNumber]` instance anymore

2021-03-08 16:40 UTC, amaalali commented on test/navigation/NavigatorSpec.scala
> -    }
Since we don't have mode anymore, should we delete the CheckMode?

2021-03-09 14:54 UTC, amaalali approved these changes

2021-03-10 12:12 UTC, merged